export const SECTORS: string[] = [
  "Indústria e Manufatura",
  "Varejo e Atacado",
  "Agronegócio",
  "Serviços Financeiros",
  "Saúde e Ciências da Vida",
  "Educação",
  "Tecnologia e Telecomunicações",
  "Energia e Utilities",
  "Construção e Imobiliário",
  "Transporte e Logística",
  "Serviços Profissionais e Empresariais",
  "Hospitalidade, Turismo e Lazer",
  "Mídia e Entretenimento",
  "Setor Público e Terceiro Setor",
  "Cooperativas e Associativismo",
  "Outro",
];
