-- Insert sample products for testing
INSERT INTO public.products (
  produto, 
  categoria, 
  description, 
  detailed_description, 
  objetivos, 
  duracao, 
  dono, 
  valor, 
  status, 
  entregas, 
  prerequisitos,
  pitch, 
  bpmn, 
  playbook, 
  icp, 
  pricing, 
  certificacao,
  pitch_url,
  bpmn_url,
  playbook_url,
  icp_url,
  pricing_url,
  certificacao_url,
  spiced_data
) VALUES 
(
  'Diagnóstico de Mídia Paga (Meta e Google Ads)',
  'saber',
  'Diagnóstico estratégico de performance em mídia paga para negócios que investem de forma consistente e desejam maximizar resultados.',
  'Análise profunda e completa de todas as campanhas de mídia paga atuais, identificando oportunidades de otimização, gaps estratégicos e pontos de melhoria para maximizar o ROI dos investimentos em Meta Ads e Google Ads.',
  'Identificar oportunidades de melhoria nas campanhas existentes; Otimizar estrutura de campanhas e segmentação; Reduzir CPA e aumentar conversões; Desenvolver estratégia de crescimento sustentável.',
  '2-3 semanas',
  'João Silva - Especialista em Performance',
  'R$ 2.500,00',
  'Disponível',
  'Relatório detalhado de diagnóstico; Planilha de otimizações prioritárias; Roadmap de implementação; Sessão de apresentação dos resultados.',
  'Ter campanhas ativas há pelo menos 3 meses; Acesso às contas de anúncios; Histórico de investimento mínimo de R$ 5.000/mês.',
  true,
  true,
  true,
  true,
  false,
  false,
  'https://docs.google.com/presentation/d/1234567890',
  'https://drive.google.com/file/d/1234567890',
  'https://notion.so/playbook-midia-paga',
  'https://docs.google.com/document/d/1234567890',
  null,
  null,
  '{"situation": "Empresa investindo em mídia paga sem resultados satisfatórios", "pain": "Alto CPA e baixo ROI nas campanhas atuais", "impact": "Perda de budget e oportunidades de crescimento", "critical_event": "Necessidade de justificar investimentos em marketing", "decision": "Contratar diagnóstico especializado para otimização"}'
),
(
  'Implementação de E-commerce',
  'ter',
  'Desenvolvimento completo de plataforma de e-commerce personalizada para acelerar vendas online.',
  'Criação de loja virtual completa com integração de pagamentos, gestão de estoque, painel administrativo e otimização para conversão. Solução escalável e responsiva.',
  'Lançar loja virtual profissional; Integrar sistemas de pagamento; Implementar gestão de estoque; Otimizar para conversões e SEO.',
  '6-8 semanas',
  'Maria Santos - Tech Lead',
  'R$ 15.000,00',
  'Disponível',
  'Plataforma e-commerce completa; Integração com gateways de pagamento; Sistema de gestão; Treinamento da equipe; 30 dias de suporte.',
  'Ter produtos/serviços definidos; Conteúdo e imagens dos produtos; Definição dos meios de pagamento; Logística de entrega estruturada.',
  true,
  true,
  true,
  true,
  true,
  false,
  'https://docs.google.com/presentation/d/2345678901',
  'https://drive.google.com/file/d/2345678901',
  'https://notion.so/playbook-ecommerce',
  'https://docs.google.com/document/d/2345678901',
  'https://docs.google.com/spreadsheets/d/2345678901',
  null,
  '{"situation": "Empresa vendendo apenas offline ou por redes sociais", "pain": "Limitação de alcance e processo de vendas manual", "impact": "Perda de vendas e dificuldade de escalar", "critical_event": "Crescimento do mercado digital e concorrência online", "decision": "Investir em plataforma e-commerce profissional"}'
),
(
  'Profissional de Google Ads',
  'executar',
  'Especialista dedicado para gestão completa de campanhas Google Ads com foco em performance.',
  'Alocação de profissional especializado para gestão estratégica e operacional das campanhas Google Ads, incluindo criação, otimização, monitoramento e reporting contínuo.',
  'Gestão profissional das campanhas; Otimização contínua de performance; Relatórios detalhados mensais; Estratégias de crescimento escalável.',
  'Contrato mensal',
  'Carlos Oliveira - Google Ads Specialist',
  'R$ 8.000,00',
  'Em Desenvolvimento',
  'Gestão completa das campanhas; Relatórios semanais de performance; Otimizações contínuas; Reuniões mensais de alinhamento.',
  'Budget mínimo de R$ 10.000/mês em anúncios; Acesso às contas Google; Briefing detalhado dos objetivos.',
  true,
  false,
  true,
  true,
  true,
  true,
  'https://docs.google.com/presentation/d/3456789012',
  null,
  'https://notion.so/playbook-google-ads',
  'https://docs.google.com/document/d/3456789012',
  'https://docs.google.com/spreadsheets/d/3456789012',
  'https://certificate.google.com/ads-specialist',
  '{"situation": "Empresa sem expertise interna em Google Ads", "pain": "Campanhas mal otimizadas e desperdício de budget", "impact": "ROI baixo e competitividade reduzida", "critical_event": "Necessidade de profissionalizar a gestão de anúncios", "decision": "Contratar especialista dedicado"}'
),
(
  'Consultoria Estratégica Avançada',
  'potencializar',
  'Análise profunda e estratégias personalizadas para empresas que buscam crescimento exponencial.',
  'Consultoria executiva focada em transformação digital, otimização de processos, desenvolvimento de estratégias de crescimento e implementação de soluções inovadoras para acelerar resultados.',
  'Desenvolver estratégia de crescimento; Otimizar processos internos; Implementar cultura data-driven; Acelerar transformação digital.',
  '12-16 semanas',
  'Ana Costa - Consultora Sênior',
  'R$ 25.000,00',
  'Disponível',
  'Diagnóstico estratégico completo; Plano de crescimento personalizado; Roadmap de implementação; Mentoria executiva; Follow-up trimestral.',
  'Faturamento mínimo de R$ 500K/mês; Equipe de gestão disponível; Abertura para mudanças estruturais.',
  true,
  true,
  true,
  true,
  true,
  false,
  'https://docs.google.com/presentation/d/4567890123',
  'https://drive.google.com/file/d/4567890123',
  'https://notion.so/playbook-consultoria',
  'https://docs.google.com/document/d/4567890123',
  'https://docs.google.com/spreadsheets/d/4567890123',
  null,
  '{"situation": "Empresa em crescimento mas com gargalos operacionais", "pain": "Dificuldade para escalar sem perder qualidade", "impact": "Crescimento limitado e oportunidades perdidas", "critical_event": "Momento de expansão ou entrada em novos mercados", "decision": "Investir em consultoria estratégica especializada"}'
),
(
  'Auditoria de Marketing Digital',
  'saber',
  'Avaliação completa da presença digital identificando oportunidades e gaps estratégicos.',
  'Análise 360° da presença digital da empresa, incluindo website, redes sociais, SEO, campanhas pagas, automação de marketing e análise da concorrência.',
  'Mapear atual presença digital; Identificar oportunidades de melhoria; Benchmarking com concorrência; Criar plano de ação priorizado.',
  '3-4 semanas',
  'Pedro Fernandes - Digital Strategist',
  'R$ 5.000,00',
  'Pausado',
  'Relatório completo de auditoria; Análise competitiva; Matriz de prioridades; Recomendações estratégicas; Apresentação executiva.',
  'Ter presença digital estabelecida; Acesso a todas as plataformas; Histórico de dados de pelo menos 6 meses.',
  true,
  false,
  true,
  false,
  false,
  false,
  'https://docs.google.com/presentation/d/5678901234',
  null,
  'https://notion.so/playbook-auditoria',
  null,
  null,
  null,
  '{"situation": "Empresa com presença digital fragmentada", "pain": "Falta de visão integrada do marketing digital", "impact": "Esforços dispersos e ROI não mensurado", "critical_event": "Necessidade de reorganizar estratégia digital", "decision": "Realizar auditoria completa para novo planejamento"}'
),
(
  'Plataforma de Automação de Vendas',
  'ter',
  'Sistema completo de CRM e automação para estruturar o processo comercial.',
  'Desenvolvimento e implementação de plataforma integrada de CRM, automação de marketing, pipeline de vendas e relatórios gerenciais para otimizar todo o processo comercial.',
  'Estruturar pipeline de vendas; Automatizar follow-ups; Integrar marketing e vendas; Gerar relatórios gerenciais automatizados.',
  '8-10 semanas',
  'Lucas Rodrigues - Sales Tech Specialist',
  'R$ 12.000,00',
  'Disponível',
  'Plataforma CRM customizada; Automações configuradas; Integrações com ferramentas existentes; Treinamento da equipe comercial.',
  'Processo de vendas mapeado; Equipe comercial definida; Integração com ferramentas atuais; Volume mínimo de 50 leads/mês.',
  true,
  true,
  true,
  true,
  true,
  false,
  'https://docs.google.com/presentation/d/6789012345',
  'https://drive.google.com/file/d/6789012345',
  'https://notion.so/playbook-automacao',
  'https://docs.google.com/document/d/6789012345',
  'https://docs.google.com/spreadsheets/d/6789012345',
  null,
  '{"situation": "Processo de vendas manual e desorganizado", "pain": "Perda de leads e baixa produtividade comercial", "impact": "Redução na taxa de conversão e crescimento limitado", "critical_event": "Crescimento da demanda e necessidade de escalar vendas", "decision": "Implementar sistema de automação profissional"}'
);